/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#5d5e60",
        "on-primary-container": "#536a00",
        "on-secondary-container": "#636467",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e2e2e4",
        "surface-variant": "#d3e4fe",
        "surface-container": "#e5eeff",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-surface-variant": "#444933",
        "on-surface": "#00272C",
        "primary-fixed-dim": "#34d399",
        outline: "#747a61",
        "on-tertiary-container": "#606264",
        "on-tertiary-fixed": "#1a1c1d",
        "secondary-container": "#e2e2e5",
        "tertiary-fixed-dim": "#c6c6c8",
        "secondary-fixed": "#e2e2e5",
        "on-primary-fixed": "#064e3b",
        "inverse-primary": "#34d399",
        background: "#00272C",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#454749",
        "on-background": "#ffffff",
        "primary-fixed": "#10b981",
        "inverse-surface": "#213145",
        "on-secondary": "#ffffff",
        "tertiary-container": "#dedee0",
        primary: "#10b981",
        "on-secondary-fixed": "#1a1c1e",
        "on-primary": "#ffffff",
        "surface-container-low": "#eff4ff",
        secondary: "#5d5e61",
        "surface-container-highest": "#d3e4fe",
        "primary-container": "#10b981",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        surface: "#00272C",
      },
    },
  },
  plugins: [],
};
